backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "precos"
    label: "Tabela de Preços"
    folder: "content/precos"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Nome do Serviço", name: "title", widget: "string"}
      - {label: "Preço (Ex: 35€)", name: "valor", widget: "string"}
      - {label: "Descrição Curta", name: "body", widget: "markdown"}