backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site"
    files:
      - name: "home"
        label: "Página Inicial"
        file: "conteudo/home.json"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Subtítulo", name: "subtitulo", widget: "string" }
