backend:
  name: github
  repo: AntonioNovatec/novatec-site
  branch: main
base_url: https://novatec-site.pages.dev
media_folder: "assets"
public_folder: "assets"

collections:
  - name: "produtos"
    label: "Produtos e Preços"
    folder: "/"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Preço", name: "price", widget: "string"}

      - {label: "Descrição", name: "body", widget: "markdown"}

